#Spring Cloud Gateway Configuration
spring:
  cloud:
    gateway:
      routes:
        - id: otp-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/signup/send-otp, /auth/signup/resend-otp, /auth/login/send-otp, /auth/login/resend-otp
          filters:
            - name: RedisRateLimiter
              args:
                routeId: otp-service
                maxRequests: 15
                durationInSeconds: 60
            - RewritePath=/(?<segment>auth/.*), /api/v1.0/${segment}

        - id: verify-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/signup/verify-otp, /auth/login/verify-otp
          filters:
            - name: RedisRateLimiter
              args:
                routeId: verify-service
                maxRequests: 10
                durationInSeconds: 60
            - RewritePath=/(?<segment>auth/.*), /api/v1.0/${segment}

        - id: refresh-token-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/refresh
          filters:
            - name: RedisRateLimiter
              args:
                routeId: refresh-token-service
                maxRequests: 20
                durationInSeconds: 60
            - RewritePath=/(?<segment>auth/.*), /api/v1.0/${segment}

        - id: token-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: RedisRateLimiter
              args:
                routeId: token-service
                maxRequests: 3
                durationInSeconds: 60
            - RewritePath=/(?<segment>auth/.*), /api/v1.0/${segment}

#        - id: auth-user-service
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/user/**
#          filters:
#            - name: RedisRateLimiter
#              args:
#                routeId: auth-user-service
#                maxRequests: 5
#                durationInSeconds: 60
#            - name: AuthFilter
#              args:
#                role: ROLE_CUSTOMER
#            - RewritePath=/(?<segment>user/.*), /api/v1.0/${segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: RedisRateLimiter
              args:
                routeId: auth-user-service
                maxRequests: 5
                durationInSeconds: 60
            - name: AuthFilter
              args:
                roles:
                  - ROLE_CUSTOMER
                  - ROLE_ADMIN
                  - ROLE_RESTAURANT_OWNER
                  - ROLE_DELIVERY_AGENT
            - RewritePath=/(?<segment>user/.*), /api/v1.0/${segment}

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - name: RedisRateLimiter
              args:
                routeId: restaurant-service
                maxRequests: 5
                durationInSeconds: 60
            - name: AuthFilter
              args:
                roles:
                  - ROLE_RESTAURANT_OWNER
            - RewritePath=/(?<segment>restaurant/.*), /api/v1.0/${segment}

        - id: menu-service
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menu/**
          filters:
            - name: RedisRateLimiter
              args:
                routeId: menu-service
                maxRequests: 5
                durationInSeconds: 60
            - name: AuthFilter
              args:
                roles:
                  - ROLE_RESTAURANT_OWNER
            - RewritePath=/(?<segment>menu/.*), /api/v1.0/${segment}

        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**
          filters:
            - name: RedisRateLimiter
              args:
                routeId: search-service
                maxRequests: 5
                durationInSeconds: 60
            - RewritePath=/(?<segment>search/.*), /api/v1.0/${segment}

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
          filters:
            - name: RedisRateLimiter
              args:
                routeId: cart-service
                maxRequests: 40
                durationInSeconds: 60
            - name: AuthFilter
              args:
                roles:
                  - ROLE_CUSTOMER
                  - ROLE_ADMIN
            - RewritePath=/(?<segment>cart/.*), /api/v1.0/${segment}

#Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost